version: "3.8"

services:
  db:
    container_name: not-boring-db
    image: postgres:latest
    env_file:
      - .env.development
    ports:
      - "5432:5432"
    restart: always
    networks:
      - my_db_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: not-boring-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@example.com"
      PGADMIN_DEFAULT_PASSWORD: "adminpassword"
    ports:
      - "5050:80"
    networks:
      - my_db_network

networks:
  my_db_network:
    driver: bridge
